/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_shandagames_android_jni_NativeSample02 */

#ifndef _Included_com_shandagames_android_jni_NativeSample02
#define _Included_com_shandagames_android_jni_NativeSample02
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_shandagames_android_jni_NativeSample02
 * Method:    callCcode
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_shandagames_android_jni_NativeSample02_callCcode
  (JNIEnv *, jobject);

/*
 * Class:     com_shandagames_android_jni_NativeSample02
 * Method:    callCcode1
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_shandagames_android_jni_NativeSample02_callCcode1
  (JNIEnv *, jobject);

/*
 * Class:     com_shandagames_android_jni_NativeSample02
 * Method:    callCcode2
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_shandagames_android_jni_NativeSample02_callCcode2
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
